export const regdata = [
    { id: "f1", name: "manual.txt", clearance: 0, size: "1.8 KB" },
    { id: "f2", name: "Sattelite.jpg", clearance: 0, size: "299 KB" },
    { id: "f3", name: "attack_rkn", clearance: 5, size: "32.3 MB" },
    { id: "f4", name: "90424.jpg", clearance: 3, size: "1.73 MB" },
    { id: "f5", name: "ZPT_relay_specs.txt", clearance: 0, size: "1.02 KB" },
    { id: "f6", name: "carrier_test_log03.txt", clearance: 0, size: "0.318 KB" },
    { id: "f7", name: "med_log_feb2026.txt", clearance: 3, size: "1.86 KB" },
    { id: "f8", name: "eeg_session_unknown.json", clearance: 5, size: "1.08 KB" },
    { id: "f9", name: "VIGIL.exe", clearance: 3, size: "236 KB" },
    { id: "f10", name: "Exif_Metadata_Reapper.exe", clearance: 3, size: "534 KB" },
    { id: "f11", name: "hidden_note.txt", clearance: 3, size: "1.20 KB" },
    { id: "f12", name: "PROJECT_RESONANCE_FINAL.txt", clearance: 5, size: "1.48 KB" },
    { id: "f13", name: "security_breach_notice.txt", clearance: 0, size: "1.18 KB" },
    { id: "f14", name: "rkn_gate_config.ini", clearance: 3, size: "0.754 KB" },
    { id: "f15", name: "glitch_test.log", clearance: 3, size: "0.936 KB" },
    { id: "f16", name: "b-12_scheme.png", clearance: 3, size: "0.701 KB" },
    { id: "f17", name: "captured_signal.mp4", clearance: 3, size: "19.8 MB" },
];
