; ZEPTA GROUP & RKN COOPERATION PROTOCOL [B-12 NODE]
; WARNING: INTERNAL USE ONLY

[GATEWAY_CONFIGURATION]
Gateway_ID = "RKN_SHIELD_V4"
Target_Segment = "VOID_RESONANCE"
Mirror_Ratio = 1.00 ; Полное зеркалирование L7-трафика
DPI_Deep_Inspect = ENABLED

[RESTRICTIONS]
Block_Unassigned_IDs = TRUE
Allowed_Core_Access = "id_obs_12"
Banned_Series = "800, 882, 885" ; Серии прототипов, подлежащие изоляции

[MONITORING_TARGETS]
; Список устройств под наблюдением (Зеркало VOID)
Target_01 = "zlom3ta@gmail.com"
Target_02 = "OBJECT_882" ; СТАТУС: ПЕРЕХВАТ ТРАФИКА АКТИВЕН

[LOGGING]
Storage_Node = "B-12_SERVER_ROOM"